### PR TITLE
modifications

### PR DESCRIPTION
**Pull request by PalashCoder**
Modified the important link section and added hover effect, modified the league logo link section, added right width for the upper banner video.

### CODE REVIEW

**Comment by Ankit-Saha08** [comment]
@iamrealpalash Thanks for ur contribution. 🤝

**Comment by PalashCoder** [comment]
React or koi front end use karne se sayad ye project aur bhi acche se aur easily work karega instead all manual code. aur mobile k liye karna bhi easy ho jayega.

**Comment by Ankit-Saha08** [comment]
Yeah, I get that. But as of now, being a starter in web-dev myself, I am trying to get my foothold strong by starting with this simple project initially. Surely, will delve into React and further development on this project soon!!

**Comment by PalashCoder** [comment]
You can contact me on linkedin as well, I'll try to contribute my best to your project

**Comment by Ankit-Saha08** [comment]
Ok surely!! 👍

**Pull request merged**
