### PR TITLE
Update IndianFootball.css

### PR DESCRIPTION
**Pull request by YashaKirad**

### CODE REVIEW

**Comment by Ankit-Saha08** [comment]
Please describe your changes in this conversation area!! Please describe clearly the changes you made for better review purpose!!

**Comment by YashaKirad** [comment]
Hi there,
I've modified the CSS file by incorporating media queries to ensure the website's responsiveness on all devices, ultimately improving its user-friendliness.

**Comment by YashaKirad** [comment]
Please accept the pull request

**Comment by Ankit-Saha08** [comment]
Please attach ss for changes of the code and result you've made!!

**Pull request closed without merging**
