### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Vanesh37**
hi @Ankit-Saha08 ,  I have done the scaling of H1 tag and uploaded changes before and  after , please check and merge it.
thank you.

https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/110464597/7b3cb6c8-6c09-4610-9781-e55558f48b16

https://github.com/Ankit-Saha08/AIFF_Live_Updates/assets/110464597/3539ef90-ce32-41a1-bb88-78af66024837

### CODE REVIEW

**Comment by Ankit-Saha08** [comment]
@Vanesh37 That was done nicely. Thanks for your contribution!!

**Comment by Vanesh37** [comment]
@Ankit-Saha08 ,  Thank you
If anything is there please feel free to tell me.

**Comment by Ankit-Saha08** [comment]
@Vanesh37 Well, if you want I can assign you with issue #10 .

**Comment by Vanesh37** [comment]
Yes,  please  assign

**Comment by Ankit-Saha08** [comment]
@Vanesh37 reply in #10 so that i can assign you there

**Comment by Vanesh37** [comment]
haa sure

**Pull request merged**
